# Generated by Django 4.2.30 on 2026-06-13 00:35

import django.core.validators
from django.db import migrations, models
import modapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('modapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(help_text='The catalog photo used to generate the ResNet50 embedding.', upload_to='clothing_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), modapp.models.validate_image_file_size]),
        ),
    ]
