# Generated by Django 4.2.30 on 2026-06-19 22:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('modapp', '0002_alter_clothingitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Machine key, e.g. 'tops'. Inferred from dataset folder name.", max_length=64, unique=True)),
                ('name', models.CharField(help_text="Human label, e.g. 'Tops'.", max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmbeddingMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('embedding_version', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Embedding Metadata',
                'verbose_name_plural': 'Embedding Metadata',
            },
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='title',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='color',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='name',
            field=models.CharField(blank=True, default='', help_text="Display name, e.g. 'Oversized Denim Jacket'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='brand',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(help_text='Catalog photo used to generate the ResNet50 embedding.', upload_to='clothing_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), modapp.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='is_indexed',
            field=models.BooleanField(db_index=True, default=False, help_text='True once the embedding is in the FAISS index.'),
        ),
        migrations.AddIndex(
            model_name='clothingitem',
            index=models.Index(fields=['is_indexed', 'created_at'], name='item_index_pending_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingitem',
            index=models.Index(fields=['category', 'is_indexed'], name='item_category_indexed_idx'),
        ),
        migrations.AddField(
            model_name='embeddingmetadata',
            name='clothing_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_metadata', to='modapp.clothingitem'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='category_slug_idx'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Garment category. NULL = uncategorised.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothing_items', to='modapp.category'),
        ),
        migrations.AddIndex(
            model_name='embeddingmetadata',
            index=models.Index(fields=['model_name', 'embedding_version'], name='embedding_model_version_idx'),
        ),
    ]
